// Homepage copy for the redesigned homepage, in the five core languages.
// Any other site language falls back to English, key by key.
export const HOME_COPY = {
  en: {
    eyebrow: 'Deals · Travel · Stays · Yachts · Cars · Events',
    titleA: 'Save on the everyday. ',
    titleEm: 'Splurge',
    titleB: ' on the extraordinary.',
    lede: 'Promo codes from {n} brands, plus yachts, villas, cars and tickets in Miami. One search and one concierge, in your language.',
    stats: ['brands with codes and offers', 'cars in our own fleet', 'yachts and villas', 'languages on the site'],
    searchLabel: 'Search or ask the concierge',
    searchPlaceholder: 'A brand, a yacht, a villa… or ask anything',
    searchGo: 'Ask',
    chipsLabel: 'Popular requests',
    chips: ['Nike code', 'Uber Eats', 'Yacht on Saturday', 'Rolls-Royce for 3 days', 'Heat tickets'],
    valet: { no: 'VALET · NO.', from: 'From', to: 'To', fromValue: 'Sunny Isles', toValue: 'South Beach', ready: 'Ready at 2:30 PM' },
    codes: 'Codes and offers',
    codesSub: 'Offers from brands you already shop. Show a code and it is copied for you.',
    showCode: 'Show code',
    copied: 'Copied',
    copyFailed: 'Select and copy',
    getDeal: 'Get deal',
    goTo: 'Go to {name}',
    withCode: 'Code',
    noCode: 'No code needed',
    ends: 'Ends {date}',
    season: 'Miami season',
    seasonSub: 'The weeks that sell out first. Plan them before everyone else does.',
    plan: 'Plan this week',
    inDays: 'In {n} days',
    tomorrow: 'Tomorrow',
    onNow: 'On now',
    organizer: 'Organizer’s site',
    seasonAsk: '{name}, {dates}. Help me plan it: a car, a place to stay, dinner and tickets.',
    seasonEmpty: 'Next season’s dates are on their way.',
    line: 'The A1A Line',
    lineSub: 'Eleven stops from Palm Beach to Key West. Pick one to see what is there.',
    airport: 'Airport',
    cruisePort: 'Cruise port',
    inland: 'Inland',
    askStop: 'Plan a day in {name}',
    askStopPrompt: 'What can I book in {name}? Cars, yachts, stays, tables and tickets.',
    worlds: 'Eight worlds. One account.',
    worldsSub: 'Every world shares one search, one saved list and one concierge.',
    worldItems: {
      deals: ['Deals', 'Promo codes and offers from everyday brands'],
      travel: ['Travel', 'Flight codes, hotels and fare tools'],
      stays: ['Stays', 'Villas and residences in Miami'],
      yachts: ['Yachts', 'Crewed charters from Miami marinas'],
      cars: ['Cars', 'Our own fleet, delivered to your door'],
      events: ['Events', 'Tickets, tables and experiences'],
      sportsbooks: ['Sportsbooks', 'Welcome offers from ten operators'],
      concierge: ['Concierge', 'Plans everything in one conversation']
    },
    counts: {
      brands: '{n} brands', flights: 'Flights · hotels', homes: '{n} homes', charters: '{n} charters',
      cars: '{n} cars', tickets: 'Tickets · nightlife', operators: '{n} operators', ai: 'AI + our team'
    },
    fleet: 'Our own fleet',
    fleetSub: '{n} cars kept in Sunny Isles Beach and delivered across Miami.',
    ratesOnRequest: 'Rates on request',
    delivered: 'Delivered across Miami',
    water: 'On the water',
    stays: 'Stays',
    seeAll: 'See all',
    conciergeEyebrow: 'Concierge',
    concierge: 'Ask in your language.',
    conciergeSub: 'Plans, codes and booking requests in one conversation. A person from our team confirms every booking.',
    open: 'Open the concierge',
    exampleLanguage: 'Example language',
    books: 'Sportsbook offers',
    booksSub: 'Ten operators, one place to compare welcome offers.',
    partnersEyebrow: 'Partners',
    partners: 'Put your brand inside Gorgona One.',
    partnersSub: 'List offers, charters, stays, cars, tables or tickets. Reach guests who are ready to book, in their language.',
    becomePartner: 'Become a partner',
    partnerSignIn: 'Partner sign in'
  },
  ru: {
    eyebrow: 'Скидки · Путешествия · Виллы · Яхты · Авто · События',
    titleA: 'Экономьте на повседневном. ',
    titleEm: 'Позвольте себе',
    titleB: ' особенное.',
    lede: 'Промокоды и скидки от {n} брендов, а ещё яхты, виллы, автомобили и билеты в Майами. Один поиск и один консьерж на вашем языке.',
    stats: ['бренды с кодами и скидками', 'машины в собственном автопарке', 'яхты и виллы', 'языки сайта'],
    searchLabel: 'Поиск или вопрос консьержу',
    searchPlaceholder: 'Бренд, яхта, вилла… или любой вопрос',
    searchGo: 'Спросить',
    chipsLabel: 'Популярные запросы',
    chips: ['Промокод Nike', 'Uber Eats', 'Яхта в субботу', 'Rolls-Royce на 3 дня', 'Билеты на Heat'],
    valet: { no: 'VALET · №', from: 'Откуда', to: 'Куда', fromValue: 'Sunny Isles', toValue: 'South Beach', ready: 'Будет готова в 14:30' },
    codes: 'Промокоды и скидки',
    codesSub: 'Предложения брендов, которыми вы уже пользуетесь. Откройте код, и он сразу скопируется.',
    showCode: 'Показать код',
    copied: 'Скопировано',
    copyFailed: 'Выделите и скопируйте',
    getDeal: 'К предложению',
    goTo: 'Перейти в {name}',
    withCode: 'Код',
    noCode: 'Код не нужен',
    ends: 'До {date}',
    season: 'Сезон Майами',
    seasonSub: 'Недели, которые раскупают первыми. Спланируйте их раньше всех.',
    plan: 'Спланировать',
    inDays: 'Через {n} дн.',
    tomorrow: 'Завтра',
    onNow: 'Идёт сейчас',
    organizer: 'Сайт организатора',
    seasonAsk: '{name}, {dates}. Помогите спланировать: машина, жильё, ужин и билеты.',
    seasonEmpty: 'Даты следующего сезона скоро появятся.',
    line: 'Линия A1A',
    lineSub: 'Одиннадцать остановок от Палм-Бич до Ки-Уэста. Выберите любую и посмотрите, что там есть.',
    airport: 'Аэропорт',
    cruisePort: 'Круизный порт',
    inland: 'Вглубь от берега',
    askStop: 'Спланировать день: {name}',
    askStopPrompt: 'Что можно забронировать в {name}? Машины, яхты, жильё, столы и билеты.',
    worlds: 'Восемь миров. Один аккаунт.',
    worldsSub: 'У всех разделов общий поиск, общее избранное и один консьерж.',
    worldItems: {
      deals: ['Скидки', 'Промокоды и предложения от повседневных брендов'],
      travel: ['Путешествия', 'Коды на авиабилеты, отели и инструменты для поиска цен'],
      stays: ['Виллы', 'Виллы и резиденции в Майами'],
      yachts: ['Яхты', 'Чартеры с экипажем из марин Майами'],
      cars: ['Авто', 'Собственный автопарк с доставкой к двери'],
      events: ['События', 'Билеты, столы и впечатления'],
      sportsbooks: ['Букмекеры', 'Приветственные предложения десяти операторов'],
      concierge: ['Консьерж', 'Планирует всё в одном диалоге']
    },
    counts: {
      brands: '{n} брендов', flights: 'Авиабилеты · отели', homes: 'Объектов: {n}', charters: 'Яхт: {n}',
      cars: 'Машин: {n}', tickets: 'Билеты · ночная жизнь', operators: '{n} операторов', ai: 'ИИ + наша команда'
    },
    fleet: 'Наш автопарк',
    fleetSub: '{n} автомобилей стоят в Sunny Isles Beach, доставляем по всему Майами.',
    ratesOnRequest: 'Цена по запросу',
    delivered: 'Доставка по Майами',
    water: 'На воде',
    stays: 'Виллы',
    seeAll: 'Смотреть всё',
    conciergeEyebrow: 'Консьерж',
    concierge: 'Спрашивайте на своём языке.',
    conciergeSub: 'Планы, промокоды и заявки на бронирование в одном диалоге. Каждую бронь подтверждает человек из нашей команды.',
    open: 'Открыть консьержа',
    exampleLanguage: 'Язык примера',
    books: 'Предложения букмекеров',
    booksSub: 'Десять операторов и их приветственные предложения в одном месте.',
    partnersEyebrow: 'Партнёрам',
    partners: 'Разместите свой бренд в Gorgona One.',
    partnersSub: 'Размещайте предложения, чартеры, жильё, машины, столы или билеты. Гости, готовые бронировать, увидят их на своём языке.',
    becomePartner: 'Стать партнёром',
    partnerSignIn: 'Вход для партнёров'
  },
  es: {
    eyebrow: 'Ofertas · Viajes · Estancias · Yates · Autos · Eventos',
    titleA: 'Ahorra en lo cotidiano. ',
    titleEm: 'Date el gusto',
    titleB: ' con lo extraordinario.',
    lede: 'Códigos promocionales de {n} marcas, además de yates, villas, autos y entradas en Miami. Una búsqueda y un concierge, en tu idioma.',
    stats: ['marcas con códigos y ofertas', 'autos de nuestra flota', 'yates y villas', 'idiomas del sitio'],
    searchLabel: 'Busca o pregunta al concierge',
    searchPlaceholder: 'Una marca, un yate, una villa… o pregunta lo que quieras',
    searchGo: 'Preguntar',
    chipsLabel: 'Búsquedas populares',
    chips: ['Código Nike', 'Uber Eats', 'Yate el sábado', 'Rolls-Royce por 3 días', 'Entradas para el Heat'],
    valet: { no: 'VALET · N.º', from: 'Desde', to: 'Hasta', fromValue: 'Sunny Isles', toValue: 'South Beach', ready: 'Listo a las 2:30 p. m.' },
    codes: 'Códigos y ofertas',
    codesSub: 'Ofertas de las marcas que ya usas. Al mostrar un código, se copia solo.',
    showCode: 'Ver código',
    copied: 'Copiado',
    copyFailed: 'Selecciona y copia',
    getDeal: 'Ver oferta',
    goTo: 'Ir a {name}',
    withCode: 'Código',
    noCode: 'Sin código',
    ends: 'Hasta el {date}',
    season: 'Temporada en Miami',
    seasonSub: 'Las semanas que se agotan primero. Planéalas antes que nadie.',
    plan: 'Planear la semana',
    inDays: 'En {n} días',
    tomorrow: 'Mañana',
    onNow: 'Ahora',
    organizer: 'Sitio del organizador',
    seasonAsk: '{name}, {dates}. Ayúdame a planearlo: auto, alojamiento, cena y entradas.',
    seasonEmpty: 'Las fechas de la próxima temporada llegarán pronto.',
    line: 'La línea A1A',
    lineSub: 'Once paradas de Palm Beach a Key West. Elige una y mira qué hay allí.',
    airport: 'Aeropuerto',
    cruisePort: 'Puerto de cruceros',
    inland: 'Tierra adentro',
    askStop: 'Planear un día en {name}',
    askStopPrompt: '¿Qué puedo reservar en {name}? Autos, yates, alojamiento, mesas y entradas.',
    worlds: 'Ocho mundos. Una cuenta.',
    worldsSub: 'Todos los mundos comparten una búsqueda, una lista de guardados y un concierge.',
    worldItems: {
      deals: ['Ofertas', 'Códigos y ofertas de marcas de todos los días'],
      travel: ['Viajes', 'Códigos de vuelos, hoteles y herramientas de tarifas'],
      stays: ['Estancias', 'Villas y residencias en Miami'],
      yachts: ['Yates', 'Chárteres con tripulación desde marinas de Miami'],
      cars: ['Autos', 'Nuestra propia flota, entregada en tu puerta'],
      events: ['Eventos', 'Entradas, mesas y experiencias'],
      sportsbooks: ['Apuestas', 'Ofertas de bienvenida de diez operadores'],
      concierge: ['Concierge', 'Lo planea todo en una sola conversación']
    },
    counts: {
      brands: '{n} marcas', flights: 'Vuelos · hoteles', homes: '{n} propiedades', charters: '{n} chárteres',
      cars: '{n} autos', tickets: 'Entradas · vida nocturna', operators: '{n} operadores', ai: 'IA + nuestro equipo'
    },
    fleet: 'Nuestra flota',
    fleetSub: '{n} autos en Sunny Isles Beach, entregados en todo Miami.',
    ratesOnRequest: 'Tarifa a consultar',
    delivered: 'Entrega en todo Miami',
    water: 'En el agua',
    stays: 'Estancias',
    seeAll: 'Ver todo',
    conciergeEyebrow: 'Concierge',
    concierge: 'Pregunta en tu idioma.',
    conciergeSub: 'Planes, códigos y solicitudes de reserva en una sola conversación. Una persona de nuestro equipo confirma cada reserva.',
    open: 'Abrir el concierge',
    exampleLanguage: 'Idioma del ejemplo',
    books: 'Ofertas de apuestas',
    booksSub: 'Diez operadores en un solo lugar para comparar ofertas de bienvenida.',
    partnersEyebrow: 'Socios',
    partners: 'Lleva tu marca a Gorgona One.',
    partnersSub: 'Publica ofertas, chárteres, estancias, autos, mesas o entradas. Llega a huéspedes listos para reservar, en su idioma.',
    becomePartner: 'Hazte socio',
    partnerSignIn: 'Acceso para socios'
  },
  pt: {
    eyebrow: 'Ofertas · Viagens · Estadias · Iates · Carros · Eventos',
    titleA: 'Economize no dia a dia. ',
    titleEm: 'Esbanje',
    titleB: ' no extraordinário.',
    lede: 'Cupons de {n} marcas, além de iates, villas, carros e ingressos em Miami. Uma busca e um concierge, no seu idioma.',
    stats: ['marcas com cupons e ofertas', 'carros da nossa frota', 'iates e villas', 'idiomas do site'],
    searchLabel: 'Busque ou pergunte ao concierge',
    searchPlaceholder: 'Uma marca, um iate, uma villa… ou pergunte o que quiser',
    searchGo: 'Perguntar',
    chipsLabel: 'Pedidos populares',
    chips: ['Cupom Nike', 'Uber Eats', 'Iate no sábado', 'Rolls-Royce por 3 dias', 'Ingressos do Heat'],
    valet: { no: 'VALET · Nº', from: 'De', to: 'Para', fromValue: 'Sunny Isles', toValue: 'South Beach', ready: 'Pronto às 14h30' },
    codes: 'Cupons e ofertas',
    codesSub: 'Ofertas das marcas que você já usa. Ao mostrar um cupom, ele é copiado para você.',
    showCode: 'Ver cupom',
    copied: 'Copiado',
    copyFailed: 'Selecione e copie',
    getDeal: 'Ver oferta',
    goTo: 'Ir para {name}',
    withCode: 'Cupom',
    noCode: 'Sem cupom',
    ends: 'Até {date}',
    season: 'Temporada em Miami',
    seasonSub: 'As semanas que esgotam primeiro. Planeje antes de todo mundo.',
    plan: 'Planejar a semana',
    inDays: 'Em {n} dias',
    tomorrow: 'Amanhã',
    onNow: 'Agora',
    organizer: 'Site do organizador',
    seasonAsk: '{name}, {dates}. Me ajude a planejar: carro, hospedagem, jantar e ingressos.',
    seasonEmpty: 'As datas da próxima temporada chegam em breve.',
    line: 'A Linha A1A',
    lineSub: 'Onze paradas de Palm Beach a Key West. Escolha uma e veja o que tem lá.',
    airport: 'Aeroporto',
    cruisePort: 'Porto de cruzeiros',
    inland: 'No interior',
    askStop: 'Planejar um dia em {name}',
    askStopPrompt: 'O que posso reservar em {name}? Carros, iates, hospedagem, mesas e ingressos.',
    worlds: 'Oito mundos. Uma conta.',
    worldsSub: 'Todos os mundos compartilham uma busca, uma lista de salvos e um concierge.',
    worldItems: {
      deals: ['Ofertas', 'Cupons e ofertas de marcas do dia a dia'],
      travel: ['Viagens', 'Cupons de voos, hotéis e ferramentas de tarifas'],
      stays: ['Estadias', 'Villas e residências em Miami'],
      yachts: ['Iates', 'Fretamentos com tripulação a partir de marinas de Miami'],
      cars: ['Carros', 'Nossa própria frota, entregue na sua porta'],
      events: ['Eventos', 'Ingressos, mesas e experiências'],
      sportsbooks: ['Apostas', 'Ofertas de boas-vindas de dez operadores'],
      concierge: ['Concierge', 'Planeja tudo em uma só conversa']
    },
    counts: {
      brands: '{n} marcas', flights: 'Voos · hotéis', homes: '{n} imóveis', charters: '{n} iates',
      cars: '{n} carros', tickets: 'Ingressos · vida noturna', operators: '{n} operadores', ai: 'IA + nossa equipe'
    },
    fleet: 'Nossa frota',
    fleetSub: '{n} carros em Sunny Isles Beach, entregues em toda Miami.',
    ratesOnRequest: 'Preço sob consulta',
    delivered: 'Entrega em toda Miami',
    water: 'No mar',
    stays: 'Estadias',
    seeAll: 'Ver tudo',
    conciergeEyebrow: 'Concierge',
    concierge: 'Pergunte no seu idioma.',
    conciergeSub: 'Planos, cupons e pedidos de reserva em uma só conversa. Uma pessoa da nossa equipe confirma cada reserva.',
    open: 'Abrir o concierge',
    exampleLanguage: 'Idioma do exemplo',
    books: 'Ofertas de apostas',
    booksSub: 'Dez operadores em um só lugar para comparar ofertas de boas-vindas.',
    partnersEyebrow: 'Parceiros',
    partners: 'Leve sua marca para a Gorgona One.',
    partnersSub: 'Anuncie ofertas, iates, estadias, carros, mesas ou ingressos. Alcance hóspedes prontos para reservar, no idioma deles.',
    becomePartner: 'Seja parceiro',
    partnerSignIn: 'Acesso de parceiros'
  },
  he: {
    eyebrow: 'מבצעים · נסיעות · לינה · יאכטות · רכבים · אירועים',
    titleA: 'חוסכים ביומיום. ',
    titleEm: 'מתפנקים',
    titleB: ' בחוויות.',
    lede: 'קודי הנחה מ־{n} מותגים, וגם יאכטות, וילות, רכבים וכרטיסים במיאמי. חיפוש אחד וקונסיירז׳ אחד, בשפה שלכם.',
    stats: ['מותגים עם קודים ומבצעים', 'רכבים בצי שלנו', 'יאכטות ווילות', 'שפות באתר'],
    searchLabel: 'חיפוש או שאלה לקונסיירז׳',
    searchPlaceholder: 'מותג, יאכטה, וילה… או כל שאלה',
    searchGo: 'שאלו',
    chipsLabel: 'בקשות פופולריות',
    chips: ['קוד Nike', 'Uber Eats', 'יאכטה בשבת', 'Rolls-Royce ל־3 ימים', 'כרטיסים ל־Heat'],
    valet: { no: 'VALET · מס׳', from: 'מ־', to: 'אל', fromValue: 'Sunny Isles', toValue: 'South Beach', ready: 'מוכן ב־14:30' },
    codes: 'קודים ומבצעים',
    codesSub: 'מבצעים מהמותגים שאתם כבר קונים בהם. חושפים קוד והוא מועתק בשבילכם.',
    showCode: 'הצגת הקוד',
    copied: 'הועתק',
    copyFailed: 'סמנו והעתיקו',
    getDeal: 'למבצע',
    goTo: 'מעבר אל {name}',
    withCode: 'קוד',
    noCode: 'ללא קוד',
    ends: 'עד {date}',
    season: 'העונה במיאמי',
    seasonSub: 'השבועות שנגמרים ראשונים. תכננו אותם לפני כולם.',
    plan: 'תכננו את השבוע',
    inDays: 'בעוד {n} ימים',
    tomorrow: 'מחר',
    onNow: 'מתקיים עכשיו',
    organizer: 'אתר המארגנים',
    seasonAsk: '{name}, {dates}. עזרו לי לתכנן: רכב, לינה, ארוחת ערב וכרטיסים.',
    seasonEmpty: 'תאריכי העונה הבאה יגיעו בקרוב.',
    line: 'קו A1A',
    lineSub: 'אחת־עשרה תחנות מפאלם ביץ׳ ועד קי וסט. בחרו תחנה וראו מה יש בה.',
    airport: 'שדה תעופה',
    cruisePort: 'נמל שייט',
    inland: 'בפנים הארץ',
    askStop: 'תכננו יום ב־{name}',
    askStopPrompt: 'מה אפשר להזמין ב־{name}? רכבים, יאכטות, לינה, שולחנות וכרטיסים.',
    worlds: 'שמונה עולמות. חשבון אחד.',
    worldsSub: 'לכל העולמות חיפוש אחד, רשימת שמורים אחת וקונסיירז׳ אחד.',
    worldItems: {
      deals: ['מבצעים', 'קודים ומבצעים ממותגים יומיומיים'],
      travel: ['נסיעות', 'קודים לטיסות, מלונות וכלים למחירים'],
      stays: ['לינה', 'וילות ודירות יוקרה במיאמי'],
      yachts: ['יאכטות', 'הפלגות עם צוות ממרינות מיאמי'],
      cars: ['רכבים', 'צי הרכבים שלנו, עד הדלת'],
      events: ['אירועים', 'כרטיסים, שולחנות וחוויות'],
      sportsbooks: ['הימורי ספורט', 'הצעות הצטרפות מעשרה מפעילים'],
      concierge: ['קונסיירז׳', 'מתכנן הכול בשיחה אחת']
    },
    counts: {
      brands: '{n} מותגים', flights: 'טיסות · מלונות', homes: '{n} נכסים', charters: '{n} יאכטות',
      cars: '{n} רכבים', tickets: 'כרטיסים · חיי לילה', operators: '{n} מפעילים', ai: 'AI + הצוות שלנו'
    },
    fleet: 'צי הרכבים שלנו',
    fleetSub: '{n} רכבים בסאני איילס ביץ׳, עם משלוח לכל מיאמי.',
    ratesOnRequest: 'מחיר לפי בקשה',
    delivered: 'משלוח לכל מיאמי',
    water: 'על המים',
    stays: 'לינה',
    seeAll: 'לכל הרשימה',
    conciergeEyebrow: 'קונסיירז׳',
    concierge: 'שאלו בשפה שלכם.',
    conciergeSub: 'תוכניות, קודים ובקשות הזמנה בשיחה אחת. אדם מהצוות שלנו מאשר כל הזמנה.',
    open: 'פתחו את הקונסיירז׳',
    exampleLanguage: 'שפת הדוגמה',
    books: 'הצעות הימורי ספורט',
    booksSub: 'עשרה מפעילים במקום אחד להשוואת הצעות הצטרפות.',
    partnersEyebrow: 'שותפים',
    partners: 'הביאו את המותג שלכם ל־Gorgona One.',
    partnersSub: 'פרסמו מבצעים, יאכטות, לינה, רכבים, שולחנות או כרטיסים. הגיעו לאורחים שמוכנים להזמין, בשפה שלהם.',
    becomePartner: 'הצטרפו כשותפים',
    partnerSignIn: 'כניסת שותפים'
  }
};

const INTL_LOCALES = { en: 'en-US', ru: 'ru-RU', es: 'es-US', pt: 'pt-BR', he: 'he-IL' };

function merge(base, override) {
  const out = { ...base };
  for (const [key, value] of Object.entries(override || {})) {
    out[key] = value && typeof value === 'object' && !Array.isArray(value) ? merge(base[key] || {}, value) : value;
  }
  return out;
}

export function getHomeCopy(locale) {
  return locale === 'en' || !HOME_COPY[locale] ? HOME_COPY.en : merge(HOME_COPY.en, HOME_COPY[locale]);
}

// Locale for dates and numbers; site languages without home copy keep their own.
export function intlLocale(locale) {
  return INTL_LOCALES[locale] || locale || 'en-US';
}

// Text for the localized line of a data record ({en, ru, ...}).
export function pickLang(map, locale) {
  return (map && (map[locale] || map.en)) || '';
}

export function fill(template, vars) {
  return Object.entries(vars).reduce((text, [key, value]) => text.split(`{${key}}`).join(String(value)), template);
}
